config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:  'pages#home'
  resources :tasks, except: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Task, user_id: user.id
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :title
  validate :future_completed_date
  validates_presence_of :user

  private

  def future_completed_date
    if !completed.blank? && completed > Date.today
      self.errors.add(:completed, "can't be in the future")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  layout :layout_by_controller

  protected

  def layout_by_controller
    devise_controller? ? 'devise' : 'application'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @tasks = Task.accessible_by(current_ability)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
    render :show_form
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    authorize! :create, @task
    save_task
  end

  def edit
    @task = Task.find(params[:id])
    authorize! :edit, @task
    render :show_form
  end

  def update
    @task = Task.find(params[:id])
    @task.assign_attributes(task_params)
    authorize! :update, @task
    save_task
  end

  def destroy
    @task = Task.find(params[:id])
    authorize! :destroy, @task
    @task.destroy
    @tasks = Task.accessible_by(current_ability)
  end

  private

  def save_task
    if @task.save
      @tasks = Task.accessible_by(current_ability)
      render :hide_form
    else
      render :show_form
    end
  end

  def task_params
    params.require(:task).permit(:title, :note, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class(flash_type)
    { success: 'alert-success',
      error:   'alert-danger',
      alert:   'alert-warning',
      notice:  'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Todo
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .row
        .jumbotron.text-center
          %h1
            ToDo
            %br
            %small Tutorial application
          = link_to 'New task', new_task_path, class: 'btn btn-primary', remote: true
          .text-center
            %strong= current_user.email
          .text-center
            = link_to 'logout', destroy_user_session_path, method: :delete
    = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title Todo
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .row
        .col-xs-10.col-xs-offset-1
          .jumbotron.text-center
            %h1
              ToDo
            %p
              Welcome to the tutorial's ToDo application
      .row
        .col-xs-4.col-xs-offset-4
          = render 'shared/flash'
      .row
        .col-xs-4.col-xs-offset-4
          = yield

app/views/pages/home.html.haml
#task-list.container
  = render partial: 'tasks/task_list', locals: {tasks: @tasks}
#modal.modal.fade

app/views/shared/_flash.html.haml
- flash.each do |type, message|
  %div{ class: "alert #{bootstrap_flash_class(type)} fade in" }
    = message
    %button.close{ data: { dismiss: 'alert' } } x

app/views/tasks/_task_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      %h1
        = task.new_record? ? 'New Task' : "Editing task #{task.title}"
    = simple_form_for task, class: 'clearfix', remote: true do |f|
      .modal-body
        = f.input :title
        = f.input :note
        = f.input :completed, as: :string, input_html: { class: 'datepicker', value: task.completed.present? ? localize(task.completed, format: '%d/%m/%Y') : nil }
      .modal-footer
        = f.submit 'Save', class: 'btn btn-primary'

app/views/tasks/_task_list.html.haml
.container
  - if @tasks.empty?
    %span.text-warning There are no tasks!
  - else
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th Title
          %th Created at
          %th Completed
          %th Actions
      %tbody
        - @tasks.each do |task|
          %tr
            %td
              %strong= task.title
            %td.text-info= task.created_at
            %td.text-success= task.completed
            %td
              = link_to task_path(task), remote: true, method: :delete, data: {confirm: "Are you sure you want to delete task #{task.title}?"} do
                %span.glyphicon.glyphicon-remove
              = link_to edit_task_path(task), remote: true do
                %span.glyphicon.glyphicon-edit

app/views/tasks/destroy.js.erb
$('#task-list').html('<%= j(render partial: 'task_list', locals: {tasks: @tasks})%>')

app/views/tasks/hide_form.js.erb
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @tasks}) %>');
$('#modal').modal('hide');

app/views/tasks/show_form.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task})%>');
m.modal('show');
$('#modal').integrateDatepicker();